### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by Nich87** [Nich87/ytd-kit#3]
# TODOs

- [ ] 高解像度のビデオのダウンロード | [Goto Code](https://github.com/Nich87/ytd-kit/blob/main/src/routes/api/ytdl/download/%2Bserver.ts)

- [ ] README.mdの作成 | [Goto Code](https://github.com/Nich87/ytd-kit/blob/main/README.md)

- [ ] コンポーネントの細分化 | [Goto Code](https://github.com/Nich87/ytd-kit/blob/main/src/routes/%2Bpage.svelte)

- [ ] [vime](https://github.com/vime-js/vime)を利用したプレビュープレイヤーの実装

**Comment by Nich87** [comment]
https://github.com/vime-js/vime/issues/301#issue-1178516901
ローカル環境では発現しないが、Vercelにデプロイするとエラーになりプレビュー不可になる。
